name: Update HA States
on:
  repository_dispatch:
    types: [ha_state_update]

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Save JSON data
        run: |
          # Tutaj zmieniliśmy na dane.json, żeby nadpisywało Twój istniejący plik
          echo '${{ toJSON(github.event.client_payload) }}' > dane.json

      - name: Commit and Push changes
        run: |
          git config --global user.name "papciop"
          git config --global user.email "ha-bot@users.noreply.github.com"
          # Tutaj też zmieniamy na dane.json, żeby Git wiedział, co dodać do commita
          git add dane.json
          
          TIMESTAMP="${{ github.event.client_payload.aktualizacja }}"
          
          # Robot sprawdzi czy w dane.json zmieniły się temperatury/statusy
          git diff-index --quiet HEAD || git commit -m "Raport $TIMESTAMP"
          git push
